# Generated by Selenium IDE
import pytest
import time
import json
import sys
import subprocess
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest01():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test01(self):
    a = subprocess.check_output(['jupyter server list'], shell=True)
    url = a.split(b'\n')[1].decode("utf-8").split(' ')[0]
    self.driver.get(url)
    self.driver.set_window_size(1280, 720)
    time.sleep(5)

    self.driver.save_screenshot("jupyterlab-extension1.png")

    self.driver.find_element(By.CSS_SELECTOR, ".jp-LauncherCard:nth-child(5) svg").click()

    self.driver.save_screenshot("jupyterlab-extension2.png")

    element = self.driver.find_element_by_xpath("//span[text()='binder']")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()

    self.driver.save_screenshot("jupyterlab-extension3.png")

    elements = self.driver.find_elements_by_class_name("makeStyles-iconButton-10")
    for el in elements:
        el.click()

    time.sleep(5)
    self.driver.save_screenshot("jupyterlab-extension4.png")

test = TestTest01()
test.setup_method('Chrome')
test.test_test01()
test.teardown_method('Chrome')

