# Generated by Selenium IDE
import pytest
import time
import json
import sys
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest01():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test01(self):
    self.driver.get(sys.argv[1])
    self.driver.set_window_size(1280, 720)
    time.sleep(5)

    self.driver.save_screenshot("jupyterlab-extension1.png")

    self.driver.find_element(By.CSS_SELECTOR, ".jp-LauncherCard:nth-child(5) svg").click()

    self.driver.save_screenshot("jupyterlab-extension2.png")

    element = self.driver.find_element_by_xpath("//span[text()='binder']")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()

    self.driver.save_screenshot("jupyterlab-extensionr3.png")

test = TestTest01()
test.setup_method('Chrome')
test.test_test01()
test.teardown_method('Chrome')

